### PR TITLE
Updated to support serverless and best practices

### PR DESCRIPTION
**Pull request by rickardl**
Brings
*  parameter groups
* serverless Support
* Cloudwatch alarms to SNS
* Removed hard coded backup routines.

## Todo

* RDS Instance Notification
* Removed redundant defaults in variables

### CODE REVIEW

**Comment by rickardl** [comment]
Reminder, remove defaults

**Comment by larstobi** [comment]
In variables.tf:
 * Unused definition source_region
 * Unused definition performance_insights_kms_key_id
 * Unused definition auto_minor_version_upgrade
 * Unused definition cloudwatch_max_replica_lag
 * Unused definition cloudwatch_eval_period_replica_lag

**Comment by larstobi** [comment]
I removed the unused variables:
```
variable "source_region" {
  description = "The source region for an encrypted replica DB cluster."
  default     = ""
}

variable "cloudwatch_eval_period_replica_lag" {
  description = "Evaluation period for the DB replica lag alarm"
  type    = number
  default = 5
}

variable "cloudwatch_max_replica_lag" {
  type        = string
  default     = "2000"
  description = "Maximum Aurora replica lag in milliseconds above which to alarm"
}

variable "performance_insights_kms_key_id" {
  description = "The ARN for the KMS key to encrypt Performance Insights data."
  type        = string
  default     = ""
}

variable "auto_minor_version_upgrade" {
  description = "Determines whether minor engine upgrades will be performed automatically in the maintenance window"
  type        = bool
  default     = true
}

```

**Review by SadriG91 — APPROVED** [review]
LGTM!

**Pull request merged**
