### PR TITLE
variable storage_encryption true by default

### PR DESCRIPTION
**Pull request by glennbech**

### CODE REVIEW

**Review by mikael-lindstrom — APPROVED** [review]
LGTM 👍 , keep in mind that this will change default behaviour so we should test what happens when this is applied (does the database become unavailable?).

**Comment by glennbech** [comment]
@mikael-lindstrom I'll test this before I merge it in.

**Comment by itsdalmo** [comment]
Did you have a chance to test this one @glennbech? 🤗

**Comment by itsdalmo** [comment]
Since terraform registry modules are always versioned, I don't think we need to test this to be honest @mikael-lindstrom. I'll just merge this and release 😄

**Pull request merged**
